# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotd < Formula
  desc "DotD is a Simple and flexible DNS over HTTPS proxy with custom resolver and other perks."
  homepage "https://github.com/adnsio/dotd"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/adnsio/dotd/releases/download/v1.0.0/dotd_1.0.0_darwin_arm64.tar.gz"
      sha256 "00e5b3e85e48a832afda405515e79c834028c8a2cdc90818438a97e2824f87e3"

      def install
        bin.install "dotd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adnsio/dotd/releases/download/v1.0.0/dotd_1.0.0_darwin_amd64.tar.gz"
      sha256 "723395b6248e3f8a7d21c20fe4cdcb0b5eaafee2e30182a6d67d2d6ed5f80e5b"

      def install
        bin.install "dotd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adnsio/dotd/releases/download/v1.0.0/dotd_1.0.0_linux_arm64.tar.gz"
      sha256 "7bff28c77e4f8bd81aa91429b109b926991e6ee5fa9a2e0be6aacff1f2cefdd3"

      def install
        bin.install "dotd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/adnsio/dotd/releases/download/v1.0.0/dotd_1.0.0_linux_armv6.tar.gz"
      sha256 "39465be3cc481a1090d6b0242cd06fa49619c21763df1fe6921d8ec5050b6e53"

      def install
        bin.install "dotd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adnsio/dotd/releases/download/v1.0.0/dotd_1.0.0_linux_amd64.tar.gz"
      sha256 "4a5005d3248b9e9e1f805c110eb6e9d484222fb2e8d26840f155bdecf24b7547"

      def install
        bin.install "dotd"
      end
    end
  end

  test do
    system "#{bin}/dotd -v"
  end
end
