# This file was generated by GoReleaser. DO NOT EDIT.
class Dotd < Formula
  desc "DotD is a Simple and flexible DNS over HTTPS proxy with custom resolver and other perks."
  homepage "https://github.com/adnsio/dotd"
  version "0.2.0-beta"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/adnsio/dotd/releases/download/v0.2.0-beta/dotd_0.2.0-beta_darwin_amd64.tar.gz"
    sha256 "0d39991acb1e4ae32fdf9f46d62cc6a5a5ae6c7f8cfe88c3c53dd804db715649"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/adnsio/dotd/releases/download/v0.2.0-beta/dotd_0.2.0-beta_linux_amd64.tar.gz"
    sha256 "89c7d2e0bf7d5400b0a3c243c3f36051b13065337f0d9d9f3efd7ad1ea1bbe3e"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/adnsio/dotd/releases/download/v0.2.0-beta/dotd_0.2.0-beta_linux_armv6.tar.gz"
    sha256 "6ceee4f1e1977abcf2c14fa854a75f6a201ee3f9a651354befab1e7ce3ce2e4c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/adnsio/dotd/releases/download/v0.2.0-beta/dotd_0.2.0-beta_linux_arm64.tar.gz"
    sha256 "77795c4087074137cc8216104da41c441d9a2105daf636877d197d4aba32209c"
  end

  def install
    bin.install "dotd"
  end

  test do
    system "#{bin}/dotd -v"
  end
end
